import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import { useEffect } from 'react';

export default function Home({ timings, date, meta }) {
  useEffect(() => {
    if (window.location.hash.includes('_token=')) {
      window.location.replace('/admin/' + window.location.hash)
    }
  })

  return (
    <>
      <Head>
        <title>Masjid Al Noor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* ChatGPT says 300-500px is ideal height for hero depending on content (h-80 is 320px) */}
      <section className="text-white h-96 relative">
        <Image src="/img/mosqueSkyUpscale.jpeg" width="2600" height="1656" alt="Mosque sunset" className="pointer-events-none absolute min-h-full min-w-full object-cover z-[-1]"/>
        <div className="pt-28 px-5">
          <div className="pb-5">
            <h3 className="whitespace-nowrap text-xl font-heading pb-3">Welcome To</h3>
            <h1 className="whitespace-nowrap text-5xl font-title">Masjid Al-Noor</h1>            
          </div>
          <div>
            <button className="block bg-green-400 p-1 rounded-lg text-center mb-2">Join Our Community</button>
            <button className="block bg-green-400 p-1 rounded-lg text-center">Donate Now</button>
          </div>
        </div>
      </section>

      <div className="container h-5 bg-gradient-to-r from-green-800 to-green-500"></div>

      <section className="py-12">
        <div className="w-10/12 mx-auto">
          <h3 className="text-3xl font-bold font-heading text-center">Our History</h3>
          <p className="text-xl font-body font-light mt-5">
            Established in 1994, Masjid Al Noor (Islamic Society of St. Catharines) is a non-profit religious organization serving the Niagara region community. Our mission is to promote and preserve the Islamic faith, culture and tradition in the province of Ontario.
          </p>
          <div className="mt-3 bg-green-400 w-4/12 text-center p-2">
            <Link href="/about"><button className="">Learn More</button></Link>
          </div>
        </div>       
      </section>

      <div className="container h-5 bg-gradient-to-r from-green-800 to-green-500"></div>

      <section className="py-12">
        <div className="w-10/12 mx-auto">
          <h3 className="text-3xl font-bold font-heading text-center">Services</h3>
          <p className="text-xl font-body font-light mt-5">
            Established in 1994, Masjid Al Noor (Islamic Society of St Catherines) is a non-profit religious organization serving the Niagara region community. Our mission is to promote and preserve the Islamic faith, culture and tradition in the province of Ontario.
          </p>
          <div className="mt-3 bg-green-400 w-4/12 text-center p-2">
            <Link href="/about"><button className="">Learn More</button></Link>
          </div>
        </div>       
      </section>

      <div className="container h-5 bg-gradient-to-r from-green-800 to-green-500"></div>

      <section className="py-12">
        <div className="w-10/12 mx-auto">
          <h3 className="text-3xl font-bold font-heading text-center">Announcements</h3>
          <p className="text-xl font-body font-light mt-5">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <div className="mt-3 bg-green-400 w-4/12 text-center p-2">
            <Link href="/about"><button className="">Learn More</button></Link>
          </div>
        </div>       
      </section>

      <div className="container h-5 bg-gradient-to-r from-green-800 to-green-500"></div>

      <section className="py-12">
        <div className="w-10/12 mx-auto">
          <h3 className="text-3xl font-bold font-heading text-center">Events</h3>
          <p className="text-xl font-body font-light mt-5">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <div className="mt-3 bg-green-400 w-4/12 text-center p-2">
            <Link href="/about"><button className="">Learn More</button></Link>
          </div>
        </div>       
      </section>

      <div className="container h-5 bg-gradient-to-r from-green-800 to-green-500"></div>

      <section className="border border-red-400 p-5">
        <h3>Contact Us</h3>
        <p className="text-md font-body">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <div>
          <button className="">Learn More</button>
        </div>
      </section>

      <div className="container h-5 bg-gradient-to-r from-green-800 to-green-500"></div>

      <section className="border border-red-400 p-5 flex">
        <div className="left">
          Al Quran
        </div>
        <div className="right">
          <div>Fajr: {timings.Fajr}</div>
          <div>Sunrise: {timings.Sunrise}</div>
          <div>Dhuhr: {timings.Dhuhr}</div>
          <div>Asr: {timings.Asr}</div>
          <div>Sunset: {timings.Sunset}</div>
          <div>Maghrib: {timings.Maghrib}</div>
          <div>Isha: {timings.Isha}</div>
        </div>          
      </section>

      <div className="container h-5 bg-gradient-to-r from-green-800 to-green-500"></div>
    </>
  )
}

export async function getStaticProps(context) {
  const res = await fetch("https://api.aladhan.com/v1/timingsByAddress?address=Al%20Noor%20Masjid,%20St.%20Catharines,%20ON");
  const data = await res.json();
  console.log(data.data)
  return {
    props: {
      timings: data.data.timings,
      date: data.data.date,
      meta: data.data.meta,
    } // will be passed to the page component as props
  }
}
