import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import { useEffect } from 'react';

import styles from '../styles/index.module.css';

export default function Home({ timings, posts }) {
  // gotta fix this
  useEffect(() => {
    if (window.location.hash.includes('_token=')) {
      window.location.replace('/admin/' + window.location.hash)
    }
  });  

  return (
    <>
      <Head>
        <title>Masjid Al Noor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-white h-screen relative overflow-hidden">
        <Image src="/img/mosqueSkyUpscale.jpeg" width="2600" height="1656" alt="Mosque sunset" className="pointer-events-none absolute min-h-full min-w-full object-cover z-[-1]"/>
        <div className="pt-28 px-5 translate-y-1/2">

          <div className={`${styles.content} mb-5`}>
            <div className={styles.content__container}>
              <ul className={`${styles.content__container__list} whitespace-nowrap text-xl font-heading pb-3`}>
                <li className={`${styles.content__container__list__item}`}><h3>Welcome to</h3></li>
                <li className={`${styles.content__container__list__item}`}><h3>مرحبا بك في</h3></li>
                <li className={`${styles.content__container__list__item}`}><h3>میں خوش آمدید</h3></li>
              </ul>
            </div>

            <h1 className="whitespace-nowrap text-5xl text-center font-title font-bold">Masjid Al-Noor</h1>

            <h3 className="text-center">Serving Niagara&apos;s Muslim Community for 30 years</h3>    
          </div>

          
          <div>
            <button className="block bg-transparent p-2 rounded-lg border-solid border-white border-2 text-center mb-2 w-3/6 mx-auto font-body">JOIN</button>
            <button className="block bg-transparent p-2 rounded-lg border-solid border-white border-2 text-center w-3/6 mx-auto font-body">GIVE</button>
          </div>
        </div>
      </section>

      <div className="p-5">
        <h2 className="text-4xl font-heading font-extrabold mb-2">Stay up to date.</h2>

        <div className="grid gap-5 grid-cols-1 grid-rows-2 sm:grid-cols-2 sm:grid-rows-1">
          <Link href="/announcements">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/announcements.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Announcements<br></br>الإعلانات
              </h3> 
            </div>
          </Link>
          
          <Link href="/events">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/events.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Events<br></br>الأحداث
              </h3>  
            </div>
          </Link>
        </div>
        
      </div>

      <div className="p-5">
        <h2 className="text-4xl font-heading font-extrabold mb-2">Get to know us.</h2>

        <div className="grid gap-5 grid-cols-1 grid-rows-2 sm:grid-cols-2 sm:grid-rows-1">
          <Link href="/services">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden">
              <Image src="/img/gridBackgrounds/services.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover rounded-lg z-[-1]"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Services<br></br>خدمات
              </h3> 
            </div>
          </Link>
          
          <Link href="/about">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden">
              <Image src="/img/gridBackgrounds/history.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                About Us<br></br>معلومات عنا
              </h3> 
            </div>
          </Link>
        </div>
      </div>

      <div className="p-5">
        <h2 className="text-4xl font-heading font-extrabold mb-2">Learn more about Islam.</h2>

        <div className="grid gap-5 grid-cols-1 grid-rows-3 sm:grid-cols-2 sm:grid-rows-2 xl:grid-cols-3 xl:grid-rows-1">
          <Link href="/resources/adhan">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/adhan.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Adhan<br></br>أذان
              </h3> 
            </div>
          </Link>
          
          <Link href="/resources/quran">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/quran.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Quran<br></br>القرآن
              </h3> 
            </div>
          </Link>
          
          <Link href="/resources/recordings" className="sm:col-span-2 xl:col-auto">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/services.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover rounded-lg z-[-1] "/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Recordings<br></br>التسجيلات
              </h3> 
            </div>
          </Link>
        </div>
        
      </div>
      
      <div className="p-5">
        <h2 className="text-4xl font-heading font-extrabold mb-2">Get involved.</h2>

        <div className="grid gap-5 grid-cols-1 grid-rows-3 sm:grid-cols-2 sm:grid-rows-2 xl:grid-cols-3 xl:grid-rows-1">
          <Link href="/donate">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/donate.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Donate<br></br>يتبرع
              </h3> 
            </div>
          </Link>
          
          <Link href="/volunteer">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/volunteer.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Volunteer<br></br>متطوع
              </h3> 
            </div>
          </Link>
          
          <Link href="/contact" className="sm:col-span-2 xl:col-auto">
            <div className="group h-[35vh] flex justify-center items-center relative block border border-gray-200 rounded-lg overflow-hidden drop-shadow-lg hover:drop-shadow-2xl">
              <Image src="/img/gridBackgrounds/contactus.jpg" width="2600" height="1656" alt="Mosque sunset" className="group-hover:blur-sm pointer-events-none absolute min-h-full min-w-full object-cover z-[-1] rounded-lg"/>
              <h3 className={`${styles.gridHeader} text-3xl font-heading font-bold text-white text-center tracking-wide`}>
                Contact Us<br></br>اتصل بنا
              </h3> 
            </div>
          </Link>
        </div>
      </div>
    </>
  )
}